language: php

php:
  - 5.5
  - 7.0
  
sudo: false  
  
before_install:
  - composer selfupdate

install: 
  - composer update
    
script:
  - phpunit

notifications:
  email:
    - yonelmeza@gmail.com

